### PR TITLE
Updated app.js to work with latest electron

### PR DESCRIPTION
**Pull request by ghost**
Replaced code with quick start code from electron site.

### CODE REVIEW

**Comment by samuelyeshua** [comment]
This has been fixed at least three times but is not embodied the repository#117 #105 #104

**Comment by forgiv** [comment]
Why haven't you just merged the changes then?

**Comment by samuelyeshua** [comment]
had not noticed before, I was waiting to see what happened and I forgot.

**Review by LumingYin — APPROVED** [review]

**Comment by pazaricha** [comment]
Will this ever be merged?

**Pull request closed without merging**
